database:
        host: xxx
        username: xxx
        password: xx@
        db_name: call_records

# table name
table_name: 'phone_numbers'

# input data format of records (query result format)
input_format: '{"name":1, "tel":2}'

AWS:
   S3:
     accessKey : yoyoy
     secretKey : paji
